
services:
  app:
    container_name: applicants
    build:
      context: .
      dockerfile: ./ApplicantsApi/Dockerfile
    ports:
      - "8080:8080"

  db:
    container_name: applicants_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=applicants_db
    ports:
      - "5432:5432"

# для того, чтобы пересобрать контейнер, если, например, поменялись конфиги:
# docker-compose up -d --build
